/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedOrgIdRouteImport } from './routes/_protected/$orgId'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestAcceptInvitationRouteImport } from './routes/_guest/accept-invitation'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account.index'
import { Route as ProtectedOrgIdIndexRouteImport } from './routes/_protected/$orgId.index'
import { Route as ProtectedAccountSecurityRouteImport } from './routes/_protected/account.security'
import { Route as ProtectedAccountMembershipsRouteImport } from './routes/_protected/account.memberships'
import { Route as ProtectedOrgIdSettingsIndexRouteImport } from './routes/_protected/$orgId.settings.index'
import { Route as ProtectedOrgIdSettingsInvitationsRouteImport } from './routes/_protected/$orgId.settings.invitations'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOrgIdRoute = ProtectedOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestAcceptInvitationRoute = GuestAcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAccountRoute,
} as any)
const ProtectedOrgIdIndexRoute = ProtectedOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedOrgIdRoute,
} as any)
const ProtectedAccountSecurityRoute =
  ProtectedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedAccountMembershipsRoute =
  ProtectedAccountMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => ProtectedAccountRoute,
  } as any)
const ProtectedOrgIdSettingsIndexRoute =
  ProtectedOrgIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedOrgIdRoute,
  } as any)
const ProtectedOrgIdSettingsInvitationsRoute =
  ProtectedOrgIdSettingsInvitationsRouteImport.update({
    id: '/settings/invitations',
    path: '/settings/invitations',
    getParentRoute: () => ProtectedOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/login': typeof GuestLoginRoute
  '/$orgId': typeof ProtectedOrgIdRouteWithChildren
  '/account': typeof ProtectedAccountRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/': typeof ProtectedIndexRoute
  '/account/memberships': typeof ProtectedAccountMembershipsRoute
  '/account/security': typeof ProtectedAccountSecurityRoute
  '/$orgId/': typeof ProtectedOrgIdIndexRoute
  '/account/': typeof ProtectedAccountIndexRoute
  '/$orgId/settings/invitations': typeof ProtectedOrgIdSettingsInvitationsRoute
  '/$orgId/settings': typeof ProtectedOrgIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof GuestAcceptInvitationRoute
  '/login': typeof GuestLoginRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/': typeof ProtectedIndexRoute
  '/account/memberships': typeof ProtectedAccountMembershipsRoute
  '/account/security': typeof ProtectedAccountSecurityRoute
  '/$orgId': typeof ProtectedOrgIdIndexRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/$orgId/settings/invitations': typeof ProtectedOrgIdSettingsInvitationsRoute
  '/$orgId/settings': typeof ProtectedOrgIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_guest/accept-invitation': typeof GuestAcceptInvitationRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_protected/$orgId': typeof ProtectedOrgIdRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/account/memberships': typeof ProtectedAccountMembershipsRoute
  '/_protected/account/security': typeof ProtectedAccountSecurityRoute
  '/_protected/$orgId/': typeof ProtectedOrgIdIndexRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/_protected/$orgId/settings/invitations': typeof ProtectedOrgIdSettingsInvitationsRoute
  '/_protected/$orgId/settings/': typeof ProtectedOrgIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/accept-invitation'
    | '/login'
    | '/$orgId'
    | '/account'
    | '/onboarding'
    | '/'
    | '/account/memberships'
    | '/account/security'
    | '/$orgId/'
    | '/account/'
    | '/$orgId/settings/invitations'
    | '/$orgId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/login'
    | '/onboarding'
    | '/'
    | '/account/memberships'
    | '/account/security'
    | '/$orgId'
    | '/account'
    | '/$orgId/settings/invitations'
    | '/$orgId/settings'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/_guest/accept-invitation'
    | '/_guest/login'
    | '/_protected/$orgId'
    | '/_protected/account'
    | '/_protected/onboarding'
    | '/_protected/'
    | '/_protected/account/memberships'
    | '/_protected/account/security'
    | '/_protected/$orgId/'
    | '/_protected/account/'
    | '/_protected/$orgId/settings/invitations'
    | '/_protected/$orgId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$orgId': {
      id: '/_protected/$orgId'
      path: '/$orgId'
      fullPath: '/$orgId'
      preLoaderRoute: typeof ProtectedOrgIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/accept-invitation': {
      id: '/_guest/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof GuestAcceptInvitationRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/$orgId/': {
      id: '/_protected/$orgId/'
      path: '/'
      fullPath: '/$orgId/'
      preLoaderRoute: typeof ProtectedOrgIdIndexRouteImport
      parentRoute: typeof ProtectedOrgIdRoute
    }
    '/_protected/account/security': {
      id: '/_protected/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof ProtectedAccountSecurityRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/account/memberships': {
      id: '/_protected/account/memberships'
      path: '/memberships'
      fullPath: '/account/memberships'
      preLoaderRoute: typeof ProtectedAccountMembershipsRouteImport
      parentRoute: typeof ProtectedAccountRoute
    }
    '/_protected/$orgId/settings/': {
      id: '/_protected/$orgId/settings/'
      path: '/settings'
      fullPath: '/$orgId/settings'
      preLoaderRoute: typeof ProtectedOrgIdSettingsIndexRouteImport
      parentRoute: typeof ProtectedOrgIdRoute
    }
    '/_protected/$orgId/settings/invitations': {
      id: '/_protected/$orgId/settings/invitations'
      path: '/settings/invitations'
      fullPath: '/$orgId/settings/invitations'
      preLoaderRoute: typeof ProtectedOrgIdSettingsInvitationsRouteImport
      parentRoute: typeof ProtectedOrgIdRoute
    }
  }
}

interface GuestRouteRouteChildren {
  GuestAcceptInvitationRoute: typeof GuestAcceptInvitationRoute
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestAcceptInvitationRoute: GuestAcceptInvitationRoute,
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface ProtectedOrgIdRouteChildren {
  ProtectedOrgIdIndexRoute: typeof ProtectedOrgIdIndexRoute
  ProtectedOrgIdSettingsInvitationsRoute: typeof ProtectedOrgIdSettingsInvitationsRoute
  ProtectedOrgIdSettingsIndexRoute: typeof ProtectedOrgIdSettingsIndexRoute
}

const ProtectedOrgIdRouteChildren: ProtectedOrgIdRouteChildren = {
  ProtectedOrgIdIndexRoute: ProtectedOrgIdIndexRoute,
  ProtectedOrgIdSettingsInvitationsRoute:
    ProtectedOrgIdSettingsInvitationsRoute,
  ProtectedOrgIdSettingsIndexRoute: ProtectedOrgIdSettingsIndexRoute,
}

const ProtectedOrgIdRouteWithChildren = ProtectedOrgIdRoute._addFileChildren(
  ProtectedOrgIdRouteChildren,
)

interface ProtectedAccountRouteChildren {
  ProtectedAccountMembershipsRoute: typeof ProtectedAccountMembershipsRoute
  ProtectedAccountSecurityRoute: typeof ProtectedAccountSecurityRoute
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
}

const ProtectedAccountRouteChildren: ProtectedAccountRouteChildren = {
  ProtectedAccountMembershipsRoute: ProtectedAccountMembershipsRoute,
  ProtectedAccountSecurityRoute: ProtectedAccountSecurityRoute,
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
}

const ProtectedAccountRouteWithChildren =
  ProtectedAccountRoute._addFileChildren(ProtectedAccountRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedOrgIdRoute: typeof ProtectedOrgIdRouteWithChildren
  ProtectedAccountRoute: typeof ProtectedAccountRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOrgIdRoute: ProtectedOrgIdRouteWithChildren,
  ProtectedAccountRoute: ProtectedAccountRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
